name: resfinder
description: CheckM provides a set of tools for assessing the quality of genomes recovered from isolates, single cells, or metagenomes.
keywords:
  - resfinder
  - amr genes
  - antimicrobial resistance
  - microbes
tools:
  - resfinder:
      description: Assess the quality of microbial genomes recovered from isolates, single cells, and metagenomes.
      homepage: https://ecogenomics.github.io/CheckM/
      documentation: https://github.com/Ecogenomics/CheckM/wiki
      tool_dev_url: https://github.com/Ecogenomics/CheckM
      doi: "10.1101/gr.186072.114"
      licence: ["GPL v3"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - input_fasta:
      type: file
      description: Input sequence for finding antimicriobial resistance genes
      pattern: "*"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - output:
      type: file
      description: "Default completeness statistics in various formats, as specified with --out_format (excluding option: 9)"
      pattern: "*.txt"

authors:
  - "@kijinkims"
