name: virsorter2_setup
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::virsorter=2.2.3
  - python >=3.6
  - ruamel.yaml =0.16.6
  - snakemake-minimal >=5.18,<=5.26
  - click >=7
  - git
  - cookiecutter
  - mamba
  - wget