custom_logo: "cidgoh.png"
custom_logo_url: https://github.com/cidgoh/bacpag/
custom_logo_title: "cidgoh/bacpaq"

title: "BACPAQ"
subtitle: "pipline"
intro_text: "bacpaq is a bioinformatics best-practice pipeline for bacterial genomic analysis for short-reads (Illumina) and long-reads (Oxford Nanopore) sequencing data. Currently nf-seqqc supports WGS-based analyses, however, we plan to integrate Microbiome (Amplicon and Shotgun Metagenomics) analyses in future."

report_comment: >
   bacpaq is a bioinformatics best-practice pipeline for bacterial genomic analysis for short-reads (Illumina) and long-reads (Oxford Nanopore) sequencing data. Currently nf-seqqc supports WGS-based analyses, however, we plan to integrate Microbiome (Amplicon and Shotgun Metagenomics) analyses in future.
 
disable_version_detection: true

report_section_order:
  "nf-core-seqqc-methods-description":
    order: -1000
  software_versions:
    order: -1001
  "nf-core-seqqc-summary":
    order: -1002

 # Run only these modules
run_modules:
  - fastqc
  - fastp
  - samtools
  - kraken
  - busco
  - quast
  - prokka

module_order:
  - fastqc:
      name: "FastQC (raw)"
      path_filters: "raw_fastqc/*.zip"
  - fastp:
      name: "FastP (Read preprocessing)"
  - fastqc:
      name: "FastQC (trim)"
      path_filters: "trim_fastqc/*.zip"
  - quast:
      name: "Quast"
  - busco:
      name: "Busco"
  - kraken:
      name: "Kraken 2"
      path_filters:
        - "*.kraken2.report.txt"
  - samtools:
      name: "Samtools Flagstat"
      info: "Summarizes the information about reads mapping to a reference genome while de-hosting. The X axis represents the proportion of each category per sample. "
  - prokka:
      name: "Prokka"

# clean names

fn_clean_exts:
  - ".gz"
  - ".fastq"

extra_fn_clean_exts:
  - type: regex
    pattern: "_T{1,2}.*"


